# Generated by Django 6.0.5 on 2026-05-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="report",
            name="report_title",
            field=models.CharField(max_length=255),
        ),
    ]
