# Generated by Django 6.0.5 on 2026-05-09 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.TextField()),
                (
                    "medicines",
                    models.TextField(help_text="Enter medicines and dosage details"),
                ),
                ("doctor_notes", models.TextField(blank=True, null=True)),
                ("ai_suggestion", models.TextField(blank=True, null=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription",
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
    ]
