# Generated by Django 6.0.5 on 2026-05-13 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("doctor_code", models.CharField(max_length=50, unique=True)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Physician"),
                            ("CARDIOLOGY", "Cardiology"),
                            ("DERMATOLOGY", "Dermatology"),
                            ("NEUROLOGY", "Neurology"),
                            ("ORTHOPEDIC", "Orthopedic"),
                            ("PEDIATRIC", "Pediatric"),
                            ("ENT", "ENT"),
                        ],
                        max_length=50,
                    ),
                ),
                ("qualification", models.CharField(max_length=255)),
                ("experience_years", models.PositiveIntegerField()),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField(blank=True, null=True)),
                ("available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
